### ISSUE TITLE
As a mobility.meran.eu user, I would like to see buses again on the map and I would like to see the version "Alpha" of the web site back functioning correctly

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#18]

**Comment by Piiit** [comment]
@rcavaliere @bertolla 

I use Firefox v63 and Linux Mint 19.0 for testing...

Tested and working:
- Busses moving and info box on click
- Walk visible inclusive numbers for groups and info box on click
- Share visible including dots and info box on click
- Rent visible and info box on click
- Charge visible including dots and info box on click
- Parking visible including dots and info box on click

Tested and not working:
- Zoom in and out continuously freezes the page, also if no data point category has been selected
^ **Can I move it to done nevertheless?** **Should I open a new issue for that?**

**Comment by rcavaliere** [comment]
Yes please
