### ISSUE TITLE
As a traveller in Bolzano, I would like to have a separate link for e-mobility and car sharing for the mobility.bz.it app (could be emobility.bz.it or mobility.bz.it/emobility, for example)

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#23]
Request by the Municipality of Bolzano

**Comment by bertolla** [comment]
@rcavaliere 
This is the easiest way I was able to accomplish the feat:
- https://mobility.bz.it
- https://bus.mobility.bz.it
- https://carsharing.mobility.bz.it
- https://emobility.mobility.bz.it
- https://parking.mobility.bz.it

**Comment by rcavaliere** [comment]
Wonderful!

**Comment by bertolla** [comment]
@RudiThoeni 
Please also check if it works and once tested move it to sprint done. Thx

**Comment by RudiThoeni** [comment]
working!
