### ISSUE TITLE
As a manager in the Merano area, I would like that mobility.meran.eu (and all other derived applications) shows the new Merano logo

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#26]

**Comment by rcavaliere** [comment]
The logo to be used is this
![merano_Black](https://user-images.githubusercontent.com/9825179/55699543-879da700-59cb-11e9-840a-b21823f4f222.png)
.

**Comment by rcavaliere** [comment]
@bertolla 
[LoghiEPS.zip](https://github.com/noi-techpark/mobility.meran.eu/files/3082049/LoghiEPS.zip)
Here the .eps logos. Can you convert them in .svg?

**Comment by bertolla** [comment]
Yes, I made it SVG
Like this:https://mobility.meran.eu/alpha/?
Also check about box and if its good with smartphone.

**Comment by bertolla** [comment]
I noticed that there is also a Favicon, which you can see in the tab. Should we change also this?
What should I use to replace it?

**Comment by rcavaliere** [comment]
Good question. I will ask Sandy, in the meantime leave it as it is.

**Comment by rcavaliere** [comment]
Tested on desktop and on mobile, seems to be fine.

**Comment by bertolla** [comment]
Ok meanwhile deployed on mobility.meran.eu

**Comment by rcavaliere** [comment]
@bertolla Sandy has told me that they have a Favicon icon. Let's wait for it so to update also this.

**Comment by ohnewein** [comment]
Favicon still missing

**Comment by ohnewein** [comment]
Sorry was a problem of caching on my client. Favicon is OK, too.
