### ISSUE TITLE
As a traveller, I would like to have to see the ratings of the users registered to the car pooling service displayed on mobility.meran.eu

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#27]
I remember the end-point of the API exposed by Innovie with the real-time data about the service:
https://hub.flootta.com/mobilitymeran/json/jUsers.json
https://hub.flootta.com/mobilitymeran/json/jServices.json

The rating information is made available through the attribute **user_rating**

In the GUI concept of Hell (see attachment, page 3 of 8) we had foreseen a number of like and dislike, which we have changed. The rating is a value ranging from 0 to 5, and should be displayed with five stars, as done by Innovie (see for example here: http://hub.flootta.com/mobilitymeran/en/board.aspx). Please note that this value is a double, so please make an approximation, as follows:
- rating 2.4 -> then two stars rating displayed
- rating 2.6 -> then three stars rating displayed

[UI_BusMeran_CarPooling.pdf](https://github.com/noi-techpark/mobility.meran.eu/files/3176410/UI_BusMeran_CarPooling.pdf)

**Comment by bertolla** [comment]
@rcavaliere 
Sure can do, but have you already requested the new icons(full start, empty start) of hell?

**Comment by rcavaliere** [comment]
@bertolla here the icons for the rating.
[Icons.zip](https://github.com/noi-techpark/mobility.meran.eu/files/3198842/Icons.zip)

**Comment by bertolla** [comment]
Can be tested on https://mobility.meran.eu/alpha/realtimebus/client/#
