### ISSUE TITLE
As a traveller, I would like to contact directly another user registered to the car pooling service into the car pooling platform of Innovie

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#28]
The URL to be inserted in the tooltip of the user while clicking on the button "Contatta" is hub.flootta.com/mobilitymeran/en/board.aspx?id_u=N

where N is the id of the user given in the method JUsers exposed by Innovie, available here:
https://hub.flootta.com/mobilitymeran/json/jUsers.json

**Comment by bertolla** [comment]
Ok I did this on https://mobility.meran.eu/alpha/realtimebus/client, but their link is not working with https.

**Comment by bertolla** [comment]
Ok now it seems to be working properly
