### ISSUE TITLE
As a project manager, I would like to have a "widget" (or better, an iframe) also for the car pooling layer, such as for example https://mobility.bz.it/widgets/?theme=carsharing for car sharing

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#29]
We need this so to embed this on the car pooling informative web page, which will be http://carpooling.bz.it/ (page to be enhanced according to the indications of local stakeholders which will coordinate the launch of the car pooling pilot)

**Comment by bertolla** [comment]
https://mobility.bz.it/widgets/?theme=carpooling should be working. Please give me feedback.

**Comment by rcavaliere** [comment]
Nice! @bertolla Can you please make an increased zoom by default on the area around Merano since the service is localized here?

**Comment by bertolla** [comment]
Merano??? this is mobility.bz.it if you want to make a zoom on merano I would do it with mobility.meran.eu

**Comment by rcavaliere** [comment]
@bertolla you are right, sorry... please apply this for mobility.meran.eu, not for mobility.bz.it....

**Comment by bertolla** [comment]
default location is south tyrol but if somebody wants to change it, it can be done through parameter e.g.:
https://mobility.meran.eu/widgets/?theme=carpooling&zoom=14&lon=1242769.68&lat=5888201.46
Coordinatesprojection is EPSG:3857
