### ISSUE TITLE
As an e-car driver I want to be able to filter by my charging provider, outlet type and station type, so that I can easily find a charging station that works for me

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#3]
Now that we will have more providers in the system, users must have clear who manage a specific charging station. Through the menu, users should have a filter with which they can decide to activate / deactivate the visualization of all charging stations of a specific provider. This search must be coupled with the existing one, that filters the data as a function of the outlet type.

**Comment by rcavaliere** [comment]
NB: Link to "payment info" should be set differently according to the provider that manages the clicked charging station.

**Comment by bertolla** [comment]
Why would a user filter by provider?

**Comment by rcavaliere** [comment]
Because an e-mobility user has typically a contract with only a provider, and can charge only in his charging stations

**Comment by rcavaliere** [comment]
Extended issue so that it is possible to filter data also as a function of the station type (private, public, private with public access).

**Comment by bertolla** [comment]
A third of the stations do not have the information of the state(private public) yet

**Comment by Piiit** [comment]
We filter as follows on the GeoServer side:
- `charging provider` by values and null (that is `undefined`)
- `outlet type` only by values (null fields are not shown)
- `station type`  by values and null (that is `undefined`)

`undefined` must be added manually to the frontend

**Comment by bertolla** [comment]
Now deployed on
http://mobility.meran.eu/widgets/?theme=emobility
and http://mobility.meran.eu/alpha
