### ISSUE TITLE
As a car pooling user I would like to have the possibility to filters users depending on the hub they want to drive. Just this hub and the related users should be visualized on map in this case

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#31]
App prototype: https://mobility.meran.eu/alpha/realtimebus/client/?l=de#

**Comment by bertolla** [comment]
The filtering now works.
Additionally if a user is selected the user and the correlated hub are being displayed in a different color like in the mockups.

**Comment by rcavaliere** [comment]
@bertolla Seems to work fine. Some bugs that we will probably need to solve with dedicated issues:
- [ ] When you click on a user, the related hub disappears from map (try user Andrea Anselmo in Trento). The hub should always be visible on the map, with the "activated" icon (dark blue).
- [x] There are still some unconsistencies between users visible on mobility.meran.eu and on Innovie car pooling visualization tool (https://hub.flootta.com/bzbga/de/board.aspx). For example, for Merano Central Station, users Martin and Stefan are not visible on mobility.meran.eu
- [x] What happens if two users give the same addresses? Is the application able to show them correctly, like for e-mobility charging stations? I think we have a case in St. Felix which shows that we have a bug.
- [x] On the filtering menu hubs should be displayed in alphabetic order

**Comment by rcavaliere** [comment]
NB: once finalized all these improvements shall be visible on the current widget, https://mobility.meran.eu/widgets/?theme=carpooling# Please note here that the filtering menu button is in a different blue colour.

**Comment by bertolla** [comment]
@rcavaliere 
About the users not displaying:
- Martin is not visible because there is no Martin exposed through https://hub.flootta.com/mobilitymeran/json/jUsers.json
- the other users are shown but since the whole layer is clusterized you need to zoom in to see them. For that I could renmove clustering for that layer

**Comment by bertolla** [comment]
About 2 or more people having the same address, I had implemented a view where the users/hubs where listed but I disabled it since I had no design for that view and thought it was no longer needed.

**Comment by rcavaliere** [comment]
For the first point, I think is a bug of Innovie, I have asked them to check this
For the second point, since we have now this case I would reintroduce it. In this case, can't we implement the same design as for e-mobility?

**Comment by bertolla** [comment]
That already should be working when clustering is available, but clustering introduces the problems we have when clicking on the icons, like the clustering of hubs and users and the dissapearing of icons

**Comment by rcavaliere** [comment]
@bertolla. Made further testing, your are right, most of the functionalities seem now to work fine. I have just seen an issue (see image): in this case when you click on a user, the icon of another user is activated in Bolzano. The correspondent hub is correctly displayed in Merano (hided by other icons).
![Issue](https://user-images.githubusercontent.com/9825179/62284557-1c815000-b454-11e9-884f-b5e3fae69900.png)

**Comment by rcavaliere** [comment]
@bertolla I also expect that when I deactivate all hubs and activate only users, the users are visible on the map. The opposite (hubs selected, users not selected) already works fine.
![Issue2](https://user-images.githubusercontent.com/9825179/62284724-7c77f680-b454-11e9-9dec-569bd4438a9f.png)

**Comment by bertolla** [comment]
> @bertolla. Made further testing, your are right, most of the functionalities seem now to work fine. I have just seen an issue (see image): in this case when you click on a user, the icon of another user is activated in Bolzano. The correspondent hub is correctly displayed in Merano (hided by other icons).
> ![Issue](https://user-images.githubusercontent.com/9825179/62284557-1c815000-b454-11e9-884f-b5e3fae69900.png)

Can't reproduce this Problem.

The second issue is fixed.

**Comment by rcavaliere** [comment]
@bertolla. The filter works fine, what is missing is that if I select a specific hub and activate drivers and passengers I expect to see only the users that want to drive to this hub

**Comment by bertolla** [comment]
@rcavaliere I think I fixed it. Tell me if the behavior is now as imagined

**Comment by bertolla** [comment]
P.S. Silvia has a long way to travel
![Hehehehe](https://user-images.githubusercontent.com/3582457/64172078-7068c580-ce54-11e9-8534-f2f7eac95c57.png)

**Comment by rcavaliere** [comment]
@bertolla No, if you click on the user you should not visualize the hub name in DE in the "Notes" section but in the "To hub" section, replacing the hub name from IT to DE when you switch the page language from IT to DE. Thanks for the advice of the user in Africa :-) The car pooling makes an automatic geocoding from the address of the user, if it is invalid it should not visualize it...

**Comment by bertolla** [comment]
I removed that behaviour. Is it ok now?
