### ISSUE TITLE
As a car pooling user I want that the information related to the hubs are displayed in the language chosen on mobility.meran.eu

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#33]

**Comment by rcavaliere** [comment]
Multi-lingual information related to hubs are available in the new end-point https://hub.flootta.com/bzbga/json/jServices.json In case of English visualization, default language is Italian (put this configurable in case we then want to put as default language German). Same functionality has to be available for the widget https://mobility.meran.eu/widgets/?theme=carpooling

**Comment by rcavaliere** [comment]
Works fine. Please just correct the reference to the hub when you click one a user.

**Comment by bertolla** [comment]
That's where we need to make another workaround because if you check the endpoint https://hub.flootta.com/bzbga/json/jUsers.json you'll see thats already wrong there. They either need to be consistent with their translations in all of their data or use references like in this case the hub id.

**Comment by rcavaliere** [comment]
Aha you are right, didn't get that you used the attribute of this method. Let put the issue in "waiting for input": when Innovie will include in the method also the attribute (hub name) also in German, then we can implement this modification.

**Comment by rcavaliere** [comment]
Modification implemented by Innovie. Please use the attribute "trip_to_name_de"

**Comment by bertolla** [comment]
Done!
