### ISSUE TITLE
As a car pooling user I would like to have the same user experience as on carpooling.bz.it

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#34]
![Bildschirmfoto 2019-06-25 um 18 33 21](https://user-images.githubusercontent.com/9825179/63034658-02b32480-beba-11e9-8251-43aada0519f3.png)
Icons must have the same basic as the new car pooling service logo (see attachment)

**Comment by rcavaliere** [comment]
Please implement this also for the car pooling widget.

**Comment by bertolla** [comment]
Waiting for markers from Hell

**Comment by rcavaliere** [comment]
Here the icons from Hell
[IconeCP.zip](https://github.com/noi-techpark/mobility.meran.eu/files/3615321/IconeCP.zip)

**Comment by rcavaliere** [comment]
@bertolla fine. can you please this and the last implemented features also on the widget?

**Comment by bertolla** [comment]
ok should be fine now
