### ISSUE TITLE
As a car pooling user if I want to contact another person I expect that the link to the car pooling platform is working fine

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#38]
Innovie has changed the URL for the API.
In the "contact person" link when you click on a user the current URL therefore does not work anymore.
What needs to be changed is just the static part of the URL
For instance:
https://hub.flootta.com/mobilitymeran/en/board.aspx?id_u=20
becomes
https://hub.flootta.com/bzbga/de/board.aspx?id_u=20

**Comment by rcavaliere** [comment]
@bertolla can you please update the correspondent widget as well?

**Comment by bertolla** [comment]
@rcavaliere done
Normally I switch these things when we go in production, that's why I haven't done it on the widgets before
