### ISSUE TITLE
As a user, I would like to see the real-time data of the new bike sharing service in Merano

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#39]
The DC now works in production, see https://ipchannels.integreen-life.bz.it/bikesharing/swagger-ui.html
We need however a small effort on the client side (mobility.meran.eu) so to visualize the data on the web-application, since the data structure is a little bit different (we do not have Bikesharingstations anymore, but only Bicycle treated as stations).

**Comment by bertolla** [comment]
https://mobility.meran.eu/alpha/#

**Comment by rcavaliere** [comment]
We need to adapt this according to our internal discussion. We should visualize both Bicycle and BikesharingStations so that both services in Bolzano and Merano are displayed correctly. Can you please do this as agreed by words, @bertolla?

**Comment by rcavaliere** [comment]
Let's implement this first for bike sharing Merano, since it has the higher priority. We will do the same in a second moment for Bolzano, since the data model is more complex. I would consider the following per Merano:
- [x] please disable the old data (data provider: algorab)

Additional meta information to be displayed if you click on the icon associated to the group of bikes):
 - [x] More info: https://www.comune.merano.bz.it/it/Bikesharing (for DE: https://www.comune.merano.bz.it/de/Bikesharing)
- [x] Origin (in the header), should be "BIKE_SHARING_MERANO"
- [x] Instead "Found multiple bikes" - "Multiple bikes available" (to be translated in the different language".
- [x] I would expect to see down the list of all available bikes in that point, the value in the "name" attribute of the table station is sufficient to identify them

**Comment by bertolla** [comment]
> * [x]  Origin (in the header), should be "BIKE_SHARING_MERANO"

Which origin? In which header?
> * [x]  I would expect to see down the list of all available bikes in that point, the value in the "name" attribute of the table station is sufficient to identify them

Wouldn't that be visually ugly and give no additional info to the enduser since they are all the same and named like 1,2,3,4... ?

**Comment by rcavaliere** [comment]
> Which origin? In which header?

In the tooltip that is opened when you click on the icon on the map, I suggest to put the information related to the attribute "origin", in the upper part of the tooltip, like a header

> Wouldn't that be visually ugly and give no additional info to the enduser since they are all the same and named like 1,2,3,4... ?

The attribute "name" returns something like "City Standard 60", which is not that ugly! This is exactly the information the users needs to understand which bikes are available. The number you see is the one attached on the bike. With the APP they have to know exactly which bike they want to open!

**Comment by bertolla** [comment]
> This is exactly the information the users needs to understand which bikes are available. 

All bikes shown on mobility.meran.eu all bikes are shown, so what is the advantage for the user?
>  With the APP they have to know exactly which bike they want to open!

If they are already using the APP(I guess a bikesharing app), why would they use mobility.meran.eu in the first place?

For the rest everything should be implemented :peace_symbol:

**Comment by rcavaliere** [comment]
> If they are already using the APP(I guess a bikesharing app), why would they use mobility.meran.eu in the first place?

Because they have also other information available (other mobility services)! Please trust me, it is useful... :-)

**Comment by rcavaliere** [comment]
@bertolla that's wonderful! Can you just add the timestamp just in the top of the tooltip, under the name?

**Comment by bertolla** [comment]
Done!
