### ISSUE TITLE
As a user, I expect to see on-spot parking data (i.e. ParkingSensors) and off-street parking data (i.e. ParkingStations) as different layers on mobility.bz.it

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#41]
Parking Sensors should be highlighted as unloading / loading bays (see icon)
![caricoscaricomerci](https://user-images.githubusercontent.com/9825179/82111095-c9f2f500-9742-11ea-9ac8-e1e421e0613f.jpg)

@bertolla can we make an estimation of the effort required? Is it a big work or should first implement the new version of the portal as web components?

It would be just the replication of the parking layer, but calling a different stationtype.

**Comment by bertolla** [comment]
Like I said multiple times, we shouldn't invest in any additional effort for the current mobility.meran.eu. It uses way to old/depreacted technology and we should focus/invest on speeding up the webcomponents version.

**Comment by rcavaliere** [comment]
OK, I agree, I thought this could be quite to implement. Let's therefore close the issue.
