### ISSUE TITLE
As a citizen of Bolzano, I would like to have a web application with all real-time information about different mobility options, so to better plan my trips in the city

### ISSUE THREAD

**Issue by rcavaliere** [idm-suedtirol/mobility.meran.eu#6]
- [x] create branch for bolzano
- [x] remove unwanted layers
- [x] Switch logo
- [x] change Bounding Box
- [ ] change About section ?????????
- [ ] deploy to??????

**Comment by rcavaliere** [comment]
The City of Bolzano would like to have "mobility.meran.eu" declined for Bolzano. The app should be called mobility.bz.it (Green Mobility of the Future web site should be moved to another URL). 
Modifications to be foreseen: different logo in the header (use "Città di Bolzano"), map centered in Bolzano, "Walk" and "Rent" layers not included. Information in "about" should be reviewed.

**Comment by ohnewein** [comment]
@rcavaliere will ask the cities of Bolzano and Merano, if we should create a single platform on province level.

**Comment by bertolla** [comment]
@rcavaliere I don't see anything that has to be changed in the About Box. Can you elaborate on that?
Where should this be deployed?

**Comment by rcavaliere** [comment]
@bertolla we will think at it afterwards. It will be just a matter of adding logos, probably.

**Comment by bertolla** [comment]
ok published to http://mobility.meran.eu/bz/
