### ISSUE TITLE
As a project manager, I would like that current widget (iframe) is visible also on 3rd parties HTTPS websites

### ISSUE THREAD

**Issue by bertolla** [idm-suedtirol/mobility.meran.eu#9]
- [x] add ssl for realtimebus.bz.it
- [x] add ssl for apiedi.tis.bz.it
- [x] point every url to https endpoint
- [x] add ssl for mobility.bz.it
- [x] request mobility.meran.eu to point to our SSL endpoint

**Comment by bertolla** [comment]
Since we do not handle the domain mobility.meran.eu we decided to move the widgets to https://mobility.bz.it/widgets for https.

**Comment by ohnewein** [comment]
Could you please update the README about this?
